export const CODE_CONTENT_SECTION_NEWS = "NEWS";
export const CODE_CONTENT_SECTION_TAGS = "TAGS";
export const CODE_CONTENT_SECTION_AUTHORS = "AUTHORS";
export const CODE_CONTENT_SECTION_USERS = "USERS";
